services:
  - type: web
    name: patchsense-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: GITHUB_PAT
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_PROJECT
        value: patchsense-prguard
      - key: LANGCHAIN_TRACING_V2
        value: "true"
